### ISSUE TITLE
Indent guides are not correct in feature file

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#146] opened 2021-07-16 13:47 UTC
PRECONDITIONS:
File | Settings | Editor | General | Appearance - Show indent guides enabled

STR:
1. Open a feature file
2. Add a scenario with **When** and **And**
3. Format it with tab

ACTUAL: Indent related to When is expanded to Then
![image](https://user-images.githubusercontent.com/48007045/125957717-8cb1999d-69a0-498c-aa30-2e9e1337bb71.png)

**Comment by Socolin** [comment] 2022-07-17 15:17
@tkapustina 

This seems to be a bug in Rider, adding a new line after and the problem is fixed

![image](https://user-images.githubusercontent.com/539620/179404871-eef044d0-41ef-41b9-aff0-28da20b9b395.png)

I can repro with C# code too

![image](https://user-images.githubusercontent.com/539620/179404886-e9246ef9-25d2-48fe-95d5-3eb6acc56bca.png)

I'm closing for now, let me know if I'm wrong about this

**Closed by Socolin** 2022-07-17 15:17 UTC
Labels: nice to have
