### ISSUE TITLE
Create Step within .feature file

### ISSUE THREAD

**Issue by dhd80** [SpecFlowOSS/SpecFlow.Rider#41] opened 2021-03-08 08:15 UTC
Hello, thanks for your awsome work at this plugin! Unfortunatly I can't create a step within the .feature file (like shown in your readme.md below the headline "Error highlight on missing step and Create Step quick fix"), see attachments.
<img width="1680" alt="Bildschirmfoto 2021-03-08 um 09 01 23" src="https://user-images.githubusercontent.com/28508999/110293239-9e513c00-7fee-11eb-8ae4-bf35f7eaa269.png">
<img width="1680" alt="Bildschirmfoto 2021-03-08 um 09 01 26" src="https://user-images.githubusercontent.com/28508999/110293251-a1e4c300-7fee-11eb-9dba-b9aed9deef06.png">

**Comment by nemesv** [comment] 2021-03-08 08:20
Duplicate of: https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/22

Currently the plugin can only create the steps in existing binding classes. 

You need add a class with the `[Binding]` attribute manually, e.g:

```
[Binding]
public class StepDefinitions
{
}
```
after that the "Create Step" quick action should pick your class.

**Closed by nemesv** 2021-03-08 08:20 UTC
Labels: enhancement
