### ISSUE TITLE
Сode completion shows irrelevant results in feature files

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#86] opened 2021-05-04 08:11 UTC
**Scenario1:**
Preconditions: an empty feature file

STR:
1. Start typing Feature in .feature
`Fe`

ACTUAL: There is no completion popup at all until Feature keyword is not available
![image](https://user-images.githubusercontent.com/48007045/116973560-68b29180-acc5-11eb-9f0f-013d1a5f09cb.png)

----
**Scenario2**
Preconditions: Feature keyword provided
`Feature:<caret>
`

STR:
1. Continue typing the feature name
`T`
`Test g`

ACTUAL: It shows irrelevant results after pressing space. The bug leads to unnecessary popup blinking during typing.
![image](https://user-images.githubusercontent.com/48007045/116975085-bb8d4880-acc7-11eb-887c-0fc55c4d5299.png)
![image](https://user-images.githubusercontent.com/48007045/116975206-ef686e00-acc7-11eb-8fd6-4cac91631284.png)

----
**Scenario3**
STR:
1. Continue typing the feature name
`c`

ACTUAL: A live template is available for completion
![image](https://user-images.githubusercontent.com/48007045/116975681-ae248e00-acc8-11eb-90dc-0d0e1d3806cf.png)

----
**Scenario4**
Preconditions: populated table
```
    Examples:
      | stars | rating |
      | 1     | Poor   |
      | 2     | Rich   |
```

STR:
1. Try to type the next row
`|3<space>`

ACTUAL: Completion popup with irrelevant results
![image](https://user-images.githubusercontent.com/48007045/116976068-4f134900-acc9-11eb-8287-bead0a39a888.png)

**Comment by Socolin** [comment] 2021-05-11 02:39
I've fixed on master Scenario 2,3,4, to fix the first one it would require more work and I don't know if this is that important for now.

**Comment by tkapustina** [comment] 2021-06-07 15:51
#1
Completion doesn't work if I start typing at the beginning of the line
![image](https://user-images.githubusercontent.com/48007045/121047583-f3a01380-c7be-11eb-87b7-04446304fa6d.png
![image](https://user-images.githubusercontent.com/48007045/121048094-29dd9300-c7bf-11eb-813b-7054036dbb99.png)


#2 
irrelevant nguid template
![image](https://user-images.githubusercontent.com/48007045/121044284-141b9e00-c7be-11eb-9c63-7d7b6fcddcb3.png)

#3
Scenario #1 is still actual but I think it might be left as it is for now.

#4
irrelevant ctx template
![image](https://user-images.githubusercontent.com/48007045/121048604-9e183680-c7bf-11eb-895f-483397d0e6e6.png)

**Comment by Socolin** [comment] 2021-06-11 02:02
Hello

About 1, this should fix the problem: https://github.com/SpecFlowOSS/SpecFlow.Rider/pull/141
About 2, I cannot reproduce, but this seems to come from a plugin or a live template
About 3, it would require a lot of change for a scenario that should not happens when using the menu "Add > Specflow Feature File" 
About 4, I can reproduce but I have no control over it (like 2)

Do you have any other plugin or live template ?

**Comment by nemesv** [comment] 2021-06-16 09:05
No 1. is fixed in Fixed in version 1.8.0.

**Comment by tkapustina** [comment] 2021-07-16 14:27
No 1 is verified
No 2, 4 are the defaults in Rider, let's skip for now and see if there will be complaints. Here is a similar issue in [F# plugin](https://youtrack.jetbrains.com/issue/RIDER-65328).
No 3 okay, got it

Btw can you make code completion case insensitive? 
Rider has a special setting for this, please, check File | Settings | Editor | General | Code Completion - Match case option.

**Comment by nemesv** [comment] 2021-07-19 09:20
I'm closing this now and created a new issue for the case sensitivity feature.

**Closed by nemesv** 2021-07-19 09:20 UTC
