### ISSUE TITLE
Inconsistent popup is used for error message about identical class names

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#134] opened 2021-06-09 09:04 UTC
STR:
1. Open .feature file
2. Create new binding class - try to add a class with the same name in the same folder

ACTUAL:
Info icon

![image](https://user-images.githubusercontent.com/48007045/121325717-83a6a000-c91a-11eb-95b9-10d6a9823e4b.png)

EXPECTED:
It would be nice to have it consistent with this message
![image](https://user-images.githubusercontent.com/48007045/121325242-1bf05500-c91a-11eb-809e-cc7eb8e3630c.png)

**Comment by nemesv** [comment] 2021-06-10 06:58
We are using a Rider built in `CreateNewFileTarget` component to add the new file to the project and this component does the validation and error message/icon internally which we cannot change. 

I was not able to find this other example in Rider, if you could tell us how to reproduce the second error message we could have a look into the code how is it done.

**Comment by tkapustina** [comment] 2021-06-10 08:20
Try to copy paste a file with the same name into the same folder
![image](https://user-images.githubusercontent.com/48007045/121490662-e876fe80-c9dd-11eb-890f-40c2d0a6221a.png)

**Comment by Socolin** [comment] 2022-07-18 00:13
All this part is in Rider code. We have no control over it, maybe somewhere else the error handling is done differently but in thie case we have no way to override it.

Since this is Rider code I think the problem should be fixed there.

```cs

  public class AddNewItemHelper
  {
    public static IProjectFile AddFile(
      [NotNull] ProjectFolderWithLocation parentFolder,
      string fileName,
      string fileText = "",
      FileCreationParameters parameters = null,
      IFileCreationContext context = null)
    {
      try
      {
        return AddNewItemHelper.AddFileOrThrow(parentFolder, fileName, fileText, parameters, context);
      }
      catch (ProjectModelEditorException ex)
      {
        MessageBox.ShowError(ex.Message, "Error");
        return (IProjectFile) null;
      }
    }
  }
```

**Closed by Socolin** 2022-07-18 00:13 UTC
Labels: nice to have
