### ISSUE TITLE
Navigate to actual feature instead of background file from Unit Tests window 

### ISSUE THREAD

**Issue by shatulsky** [SpecFlowOSS/SpecFlow.Rider#84] opened 2021-04-27 11:13 UTC
On Visual studio double-click on test in 'Test explorer' window opens actual scenario in .feature file.
On Rider double-click on test in 'Unit Tests' window opens autogenerated code in .feature.cs file.

Version:
SpecFlow for Rider 1.6.0
SpecFlow 3.5.14
SpecFlow.NUnit 3.5.14
SpecFlow.Tools.MsBuild.Generation 3.5.14
MSTest.TestFramework 2.2.2
Microsoft.NET.Test.Sdk 16.8.3
NUnit.Engine 3.11.1
NUnit 3.13.0
NUnit3TestAdapter 3.17.0

**Comment by nemesv** [comment] 2021-04-27 19:16
Duplicate of #37

**Closed by nemesv** 2021-04-27 19:16 UTC
