### ISSUE TITLE
System.ExecutionEngineException thrown when trying to debug tests

### ISSUE THREAD

**Issue by mrt181** [SpecFlowOSS/SpecFlow.Rider#166] opened 2022-02-17 11:30 UTC
This is the exception message:

`Exception of type 'System.ExecutionEngineException' was thrown.`

StackTrace is `null`.

Normal Unit test runs work.

I have attached the log file:
[2022-02-17-12-14-40-072___ae185480-ac9d-4dc8-b881-83c4213b90cb.log](https://github.com/SpecFlowOSS/SpecFlow.Rider/files/8088218/2022-02-17-12-14-40-072___ae185480-ac9d-4dc8-b881-83c4213b90cb.log)

I am using 
`JetBrains Rider 2021.3.3 Build #RD-213.6775.4, built on January 26, 2022` and 
`SpecFlow for Rider 1.10.2`

**Comment by Socolin** [comment] 2022-02-19 05:20
Is it happening for one specific test or any specflow test ?
If you disable the plugin then restart, if you run the test from thje rider test runner does it fail too ?

**Comment by mrt181** [comment] 2022-02-19 15:02
Any Specflow Test.
It fails also when disabling the plugin.
This is one message I also get:
```
An IL variable is not available at the current native IP. The error code is CORDBG_E_IL_VAR_NOT_AVAILABLE, or0x80131304.
```

Debuggin a simple pure, Xunit test throws the same exception, problem seems to be there.

**Comment by Socolin** [comment] 2022-07-17 01:56
So I'm closing this one seems it seems the problem is not in the plugin

**Closed by Socolin** 2022-07-17 01:56 UTC
